Config = {}

Config.Locale = "fr"

-- Limit, unit can be whatever you want. Originally grams (as average people can hold 25kg)
Config.Weight = 25000

-- Default weight for an item:
-- weight == 0 : The item do not affect character inventory weight
-- weight > 0 : The item cost place on inventory
-- weight < 0 : The item add place on inventory. Smart people will love it.
Config.DefaultWeight = 1

Config.Vehicule = { 
    Compacts = { 
        { model = "blista", weight = 100 },
        { model = "blista2", weight = 300 },
        { model = "brioso", weight = 100 },
        { model = "brioso2", weight = 100 },
        { model = "dilettante", weight = 100 }, 
        { model = "issi2", weight = 100 }, 
        { model = "issi3", weight = 100 }, 
        { model = "panto", weight = 100 }, 
        { model = "prairie", weight = 100 }, 
        { model = "rhapsody", weight = 100 },
        { model = "asbo", weight = 100 },
        { model = "kanjo", weight = 100 },
        { model = "club", weight = 100 },
        { model = "weevil", weight = 100 },
    },
    Coupes = {
        { model = "cogcabrio", weight = 300 },
        { model = "exemplar", weight = 300 },
        { model = "f620", weight = 300 },
        { model = "felon", weight = 300 },
        { model = "felon2", weight = 300 },
        { model = "jackal", weight = 300 },
        { model = "oracle", weight = 300 },
        { model = "oracle2", weight = 300 },
        { model = "sentinel", weight = 300 },
        { model = "sentinel2", weight = 300 },
        { model = "windsor", weight = 300 },
        { model = "windsor2", weight = 300 },
        { model = "zion", weight = 300 },
        { model = "zion2", weight = 300 },
        { model = "previon", weight = 300 },
    },
    Motos = {
        { model = "akuma", weight = 50 },
        { model = "avarus", weight = 50 },
        { model = "bagger", weight = 50 },
        { model = "bati", weight = 50 },
        { model = "bati2", weight = 50 }, 
        { model = "bf400", weight = 50 },
        { model = "carbonrs", weight = 50 },
        { model = "chimera", weight = 50 },
        { model = "cliffhanger", weight = 50 },
        { model = "daemon", weight = 50 },
        { model = "daemon2", weight = 50 },
        { model = "defiler", weight = 50 },
        { model = "diablous", weight = 50 },
        { model = "diablous2", weight = 50 },
        { model = "double", weight = 50 },
        { model = "enduro", weight = 50 },
        { model = "esskey", weight = 50 },
        { model = "faggio", weight = 50 },
        { model = "faggio2", weight = 50 },
        { model = "faggio3", weight = 50 }, 
        { model = "fcr", weight = 50 },
        { model = "fcr2", weight = 50 },
        { model = "gargoyle", weight = 50 },
        { model = "hakuchou", weight = 50 },
        { model = "hakuchou2", weight = 50 },
        { model = "hexer", weight = 50 },
        { model = "innovation", weight = 50 },
        { model = "lectro", weight = 50 },
        { model = "manchez", weight = 50 },
        { model = "manchez2", weight = 50 },
        { model = "nemesis", weight = 50 },
        { model = "nightblade", weight = 50 },
        { model = "pcj", weight = 50 },
        { model = "ratbike", weight = 50 },
        { model = "ruffian", weight = 50 },
        { model = "sanctus", weight = 50 },
        { model = "sovereign", weight = 50 },
        { model = "thrust", weight = 50 },
        { model = "vader", weight = 50 },
        { model = "vindicator", weight = 50 },
        { model = "vortex", weight = 50 },
        { model = "wolfsbane", weight = 50 },
        { model = "zombiea", weight = 50 },
        { model = "zombieb", weight = 50 },
        { model = "sanchez", weight = 50 },
        { model = "sanchez2", weight = 50 },
        { model = "stryder", weight = 50 },
        { model = "shinobi", weight = 50 },
        { model = "reever", weight = 50 },
    },
    Muscles = {
        { model = "blade", weight = 250 },
        { model = "buccaneer", weight = 250 },
        { model = "buccaneer2", weight = 250 },
        { model = "chino", weight = 250 },
        { model = "chino2", weight = 250 },
        { model = "clique", weight = 300 },
        { model = "coquette3", weight = 250 },
        { model = "deviant", weight = 300 },
        { model = "dominator", weight = 350 },
        { model = "dominator2", weight = 350 },
        { model = "dominator3", weight = 350 },
        { model = "dukes", weight = 250 },
        { model = "ellie", weight = 250 },
        { model = "faction", weight = 250 },
        { model = "faction2", weight = 250 },
        { model = "faction3", weight = 250 },
        { model = "ellie", weight = 250 },
        { model = "gauntlet", weight = 300 },
        { model = "gauntlet2", weight = 300 },
        { model = "gauntlet3", weight = 300 },
        { model = "gauntlet4", weight = 300 },
        { model = "hermes", weight = 250 },
        { model = "hotknife", weight = 200 },
        { model = "hustler", weight = 200 },
        { model = "nightshade", weight = 250 },
        { model = "impaler", weight = 400 },
        { model = "impaler2", weight = 400 },
        { model = "imapaler3", weight = 400 },
        { model = "peyote2", weight = 250 },
        { model = "phoenix", weight = 300 },
        { model = "picador", weight = 250 },
        { model = "ratloader", weight = 350 }, 
        { model = "ratloader2", weight = 350 },
        { model = "ruiner", weight = 250 },
        { model = "sabregt", weight = 300 },
        { model = "sabregt2", weight = 300 },
        { model = "slamvan", weight = 400 },
        { model = "slamvan2", weight = 400 },
        { model = "slamvan3", weight = 400 },
        { model = "stalion", weight = 250 },
        { model = "stalion2", weight = 250 },
        { model = "tampa", weight = 250 },
        { model = "tulip", weight = 350 },
        { model = "vamos", weight = 250 },
        { model = "vigero", weight = 250 },
        { model = "virgo", weight = 250 },
        { model = "virgo2", weight = 250 },
        { model = "virgo3", weight = 250 },
        { model = "voodoo", weight = 250 },
        { model = "voodoo2", weight = 250 },
        { model = "dominator7", weight = 250 },
        { model = "yosemite", weight = 400 },
        { model = "yosemite2", weight = 400 },
         { model = "yosemite3", weight = 400 },
    },
    Offroad = { 
        { model = "bfinjection", weight = 100 },
        { model = "bifta", weight = 100 },
        { model = "blazer", weight = 50 },
        { model = "blazer2", weight = 50 },
        { model = "blazer3", weight = 50 },
        { model = "blazer4", weight = 50 },
        { model = "blazer5", weight = 50 },
        { model = "bodhi2", weight = 150 },
        { model = "brawler", weight = 250 },
        { model = "trophytruck", weight = 500 },
        { model = "trophytruck2", weight = 500 },
        { model = "caracara2", weight = 600 },
        { model = "dloader", weight = 150 },
        { model = "dubsta3", weight = 600 },
        { model = "everon", weight = 600 },
        { model = "freecrawler", weight = 250 },
        { model = "guardian", weight = 500 },
        { model = "hellion", weight = 600 },
        { model = "kalahari", weight = 150 },
        { model = "kamacho", weight = 550 },
        { model = "mesa3", weight = 100 },
        { model = "outlaw", weight = 100 },
        { model = "raptor", weight = 150 },
        { model = "rancherxl", weight = 150 },
        { model = "rebel", weight = 150 },
        { model = "rebel2", weight = 150 },
        { model = "riata", weight = 150 },
        { model = "sandking", weight = 550 },
        { model = "sandking2", weight = 550 },
        { model = "vagrant", weight = 100 },
        { model = "verus", weight = 5 },
        { model = "winky", weight = 100 },
    },
SportivesClassiques = {
        { model = "ardent", weight = 100 },
        { model = "btype", weight = 100 },
        { model = "btype2", weight = 100 },
        { model = "btype3", weight = 100 },
        { model = "casco", weight = 100 },
        { model = "cheburek", weight = 150 },
        { model = "chettah2", weight = 100 },
        { model = "coquette2", weight = 100 },
        { model = "dynasty", weight = 100 },
        { model = "fagaloa", weight = 100 },
        { model = "feltzer3", weight = 100 },
        { model = "gt500", weight = 100 },
        { model = "infernus2", weight = 100 },
        { model = "jb7002", weight = 100 },
        { model = "mamba", weight = 100 },
        { model = "manana", weight = 100 },
        { model = "manana2", weight = 100 },
        { model = "michelli", weight = 100 },
        { model = "monroe", weight = 100 },
        { model = "nebula", weight = 100 },
        { model = "peyote", weight = 100 },
        { model = "peyote3", weight = 100 },
        { model = "pigalle", weight = 100 },
        { model = "rapidgt3", weight = 100 },
        { model = "retinue", weight = 100 },
        { model = "retinue2", weight = 100 },
        { model = "savestra", weight = 100 },
        { model = "stinger", weight = 100 },
        { model = "stingergt", weight = 100 },
        { model = "swinger", weight = 100 },
        { model = "tornado", weight = 100 },
        { model = "tornado2", weight = 100 },
        { model = "tornado3", weight = 100 },
        { model = "tornado4", weight = 100 },
        { model = "tornado5", weight = 100 },
        { model = "tornado6", weight = 100 },
        { model = "turismo2", weight = 150 },
        { model = "viseris", weight = 150 },
        { model = "torero", weight = 150 },
        { model = "z190", weight = 100 },
        { model = "zion3", weight = 100 },
        { model = "ztype", weight = 100 },
    },
    Sportives = {
        { model = "ninef", weight = 150 },
        { model = "ninef2", weight = 150 },
        { model = "alpha", weight = 200 },
        { model = "banshee", weight = 150 },
        { model = "bestiagts", weight = 200 },
        { model = "buffalo", weight = 300 },
        { model = "buffalo2", weight = 300 },
        { model = "buffalo3", weight = 300 },
        { model = "buffalo5", weight = 300 },
        { model = "carbonizzare", weight = 150 },
        { model = "comet2", weight = 150 },
        { model = "comet3", weight = 150 },
        { model = "comet4", weight = 150 },
        { model = "comet5", weight = 150 },
        { model = "comet6", weight = 150 },
        { model = "comet7", weight = 150 },
        { model = "coquette4", weight = 150 },
        { model = "coquette", weight = 150 },
        { model = "drafter", weight = 150 },
        { model = "elegy", weight = 150 },
        { model = "elegy2", weight = 150 },
        { model = "feltzer2", weight = 150 },
        { model = "flashgt", weight = 150 },
        { model = "furoregt", weight = 150 },
        { model = "fusilade", weight = 150 },
        { model = "futo", weight = 150 },
        { model = "gb200", weight = 150 },
        { model = "hotring", weight = 150 },
        { model = "issi7", weight = 150 },
        { model = "italigto", weight = 150 },
        { model = "jester", weight = 150 },
        { model = "jester2", weight = 150 },
        { model = "jugular", weight = 300 },
        { model = "khamelion", weight = 150 },
        { model = "kuruma", weight = 300 },
        { model = "locust", weight = 150 },
        { model = "lynx", weight = 150 },
        { model = "massacro", weight = 150 },
        { model = "massacro2", weight = 150 },
        { model = "neo", weight = 150 },
        { model = "neon", weight = 150 },
        { model = "omnis", weight = 150 },
        { model = "paragon", weight = 150 },
        { model = "pariah", weight = 150 },
        { model = "penumbra", weight = 150 },
        { model = "raiden", weight = 300 },
        { model = "rapidgt", weight = 150 },
        { model = "rapidgt2", weight = 150 },
        { model = "ruston", weight = 150 },
        { model = "revolter", weight = 150 },
        { model = "schafter2", weight = 300 },
        { model = "schafter3", weight = 300 },
        { model = "schafter4", weight = 300 },
        { model = "schlagen", weight = 150 },
        { model = "specter", weight = 150 },
        { model = "specter2", weight = 150 },
        { model = "schwarzer", weight = 200 },
        { model = "sentinel3", weight = 200 },
        { model = "seven70", weight = 150 },
        { model = "sultan", weight = 150 },
        { model = "sultan2", weight = 150 },
        { model = "surano", weight = 150 },
        { model = "tampa2", weight = 150 },
        { model = "tropos", weight = 150 },
        { model = "rt3000", weight = 150 },
        { model = "verlierer2", weight = 150 },
        { model = "vectre", weight = 150 },
        { model = "futo2", weight = 150 },
        { model = "calico", weight = 150 },
        { model = "zr350", weight = 150 },
        { model = "jester4", weight = 150 },
        { model = "euros", weight = 150 },
        { model = "sultan3", weight = 300 },
        { model = "remus", weight = 150 },  
        { model = "jester3", weight = 150 },
        { model = "growler", weight = 150 },
        { model = "sugoi", weight = 300 },
        { model = "vstr", weight = 300 },
        { model = "cypher", weight = 150 },
        { model = "deity", weight = 150 },
    },
    SuperSportives = {
        { model = "adder", weight = 100 },
        { model = "autarch", weight = 150 },
        { model = "banshee2", weight = 100 },
        { model = "bullet", weight = 100 },
        { model = "cheetah", weight = 150 },
        { model = "cyclone", weight = 100 },
        { model = "deveste", weight = 150 },
        { model = "emerus", weight = 150 },
        { model = "entityxf", weight = 100 },
        { model = "entity2", weight = 150 },
        { model = "fmj", weight = 100 },
        { model = "gp1", weight = 100 },
        { model = "infernus", weight = 100 },
        { model = "italigtb", weight = 100 },
        { model = "italigtb2", weight = 100 },
        { model = "krieger", weight = 100 },
        { model = "nero", weight = 100 },
        { model = "nero2", weight = 100 },
        { model = "osiris", weight = 100 },
        { model = "penetrator", weight = 100 },
        { model = "pfister811", weight = 100 },
        { model = "prototipo", weight = 150 },
        { model = "reaper", weight = 150 },
        { model = "sc1", weight = 150 },
        { model = "sultanrs", weight = 150 },
        { model = "t20", weight = 150 },
        { model = "taipan", weight = 150 },
        { model = "tempesta", weight = 150 },
        { model = "tezeract", weight = 150 },
        { model = "thrax", weight = 150 },
        { model = "turismor", weight = 150 },
        { model = "tyrant", weight = 150 },
        { model = "tyrus", weight = 150 },
        { model = "vacca", weight = 150 },
        { model = "vagner", weight = 150 },
        { model = "visione", weight = 150 },
        { model = "voltic", weight = 50 },
        { model = "xa21", weight = 150 },
        { model = "zentorno", weight = 150 },
        { model = "zorrusso", weight = 150 },
        { model = "komoda", weight = 150 },
        { model = "imorgon", weight = 150 },
        { model = "italirsx", weight = 150 },
        { model = "ignus", weight = 150 },
    },
    Vans = {
        {model = "bison", weight = 400 },
        {model = "bobcatxl", weight = 200 },
        {model = "burrito3", weight = 1000 },
        {model = "gburrito2", weight = 1000 },
        {model = "camper", weight = 800 },
        {model = "gburrito", weight = 1000 },
        {model = "journey", weight = 400 },
        {model = "moonbeam", weight = 1000 },
        {model = "moonbeam2", weight = 1000 },
        {model = "paradise", weight = 400 },
        {model = "rumpo", weight = 1000 },
        {model = "surfer", weight = 300 },
        {model = "youga", weight = 1000 },
        {model = "youga2", weight = 1000 },
        {model = "youga3", weight = 1000 },
        {model = "speedo", weight = 1000 },
    },
    Berlines = {
        {model = "tailgater2", weight = 200 },
        {model = "asea", weight = 200 },
        {model = "asterope", weight = 200 },
        {model = "cognoscenti", weight = 300 },
        {model = "cog55", weight = 200 },
        {model = "emperor", weight = 200 },
        {model = "emperor2", weight = 200 },
        {model = "fugitive", weight = 350 },
        {model = "glendale", weight = 350 },
        {model = "glendale2", weight = 350 },
        {model = "ingot", weight = 200 },
        {model = "stafford", weight = 200 },
        {model = "stanier", weight = 200 },
        {model = "stretch", weight = 200 },
        {model = "intruder", weight = 350 },
        {model = "surge", weight = 200 },
        {model = "premier", weight = 200 },
        {model = "primo", weight = 300 },
        {model = "primo2", weight = 350 },
        {model = "regina", weight = 300 },
        {model = "schafter2", weight = 300 },
        {model = "superd", weight = 200 },
        {model = "tailgater", weight = 200 },
        {model = "warrener", weight = 250 },
        {model = "washington", weight = 250 },
    },
    SUVs = {
        { model = "baller", weight = 600 },
        { model = "baller2", weight = 600 },
        { model = "baller3", weight = 600 },
        { model = "baller4", weight = 600 },
        { model = "bjxl", weight = 400 },
        { model = "cavalcade", weight = 500 },
        { model = "cavalcade2", weight = 500 },
        { model = "contender", weight = 700 },
        { model = "dubsta", weight = 500 },
        { model = "dubsta2", weight = 500 },
        { model = "fq2", weight = 500 },
        { model = "granger", weight = 600 },
        { model = "granger2", weight = 900 },
        { model = "gresley", weight = 500 },
        { model = "habanero", weight = 500 },
        { model = "huntley", weight = 400 },
        { model = "streiter", weight = 400 },
        { model = "landstalker", weight = 500 },
        { model = "landstalker2", weight = 500 },
        { model = "mesa", weight = 400 },
        { model = "novak", weight = 750 },
        { model = "patriot", weight = 500 },
        { model = "patriot2", weight = 500 },
        { model = "radi", weight = 300 },
        { model = "seminole2", weight = 300 },
        { model = "rocoto", weight = 600 },
        { model = "radi", weight = 300 },
        { model = "seminole", weight = 500 },
        { model = "serrano", weight = 400 },
        { model = "toros", weight = 400 },
        { model = "xls", weight = 750 },
        { model = "rebla", weight = 750 },
        { model = "iwagen", weight = 700 },
        { model = "jubilee", weight = 700 },
        { model = "astron", weight = 250 },
    },
    LSFD = { 
        { model = "lsfd", weight = 100 },
        { model = "lsfd2", weight = 100 },
        { model = "lsfd3", weight = 100 },
        { model = "lsfd4", weight = 100 },
        { model = "lsfd5", weight = 100 },
        { model = "lsfdtruck", weight = 100 },
        { model = "lsfdtruck2", weight = 100 },
        { model = "lsfdtruck3", weight = 100 },
        { model = "mocpacker2", weight = 100 },
    },
    LSPD = { 
        { model = "lspdb", weight = 300 },
        { model = "police", weight = 300 },
        { model = "police2", weight = 300 },
        { model = "police3", weight = 300 },
        { model = "police4", weight = 300 },
        { model = "polalamoold", weight = 600 },
        { model = "poleveron", weight = 700 },
        { model = "police42old", weight = 400 },
        { model = "policeold", weight = 700 },
        { model = "policeslick", weight = 300 },
        { model = "polriot", weight = 1000 },
        { model = "polsadlerk9", weight = 700 },
        { model = "polspeedo", weight = 1000 },
        { model = "pscout", weight = 500 },
        { model = "pscoutnew", weight = 500 },
        { model = "swatstalker", weight = 500 },
        { model = "mocpacker", weight = 1000 },
    },
    LSSD = { 
        { model = "sheriff", weight = 300 },
        { model = "sheriff2", weight = 300 },
        { model = "sheriffalamo", weight = 500 },
        { model = "sheriffcq4", weight = 100 },
        { model = "sherifffug", weight = 300 },
        { model = "sheriffinsurgent", weight = 1000 },
        { model = "sheriffoss", weight = 300 },
        { model = "sheriffroamer", weight = 500 },
        { model = "sheriffrumpo", weight = 700 },
        { model = "sheriffscout", weight = 500 },
        { model = "sheriffscoutnew", weight = 500 },
        { model = "sheriffstalker", weight = 500 },
        { model = "sheriffthrust", weight = 50 },  
    },
    SERV = { 
        { odel = "airbus", weight = 1000 },
        { model = "bus", weight = 1000 },
        { model = "coach", weight = 1000 },
        { model = "pbus2", weight = 1000 },
        { model = "rentalbus", weight = 800 },
        { model = "taxi", weight = 300 },
        { model = "trash2", weight = 1000 },
        { model = "boxville2", weight = 1000 },
        { model = "boxville4", weight = 1000 },
        { model = "bison3", weight = 700 },
        { model = "taco", weight = 1000 },
        { model = "speedo4", weight = 1000 },
        { model = "speedo", weight = 1000 },
    },
    USSS = { 
        { model = "cat", weight = 500 },
        { model = "halfback", weight = 500 },
        { model = "halfback2", weight = 500 },
        { model = "hazard", weight = 1000 },
        { model = "hazard2", weight = 1000 },
        { model = "idcar", weight = 500 },
        { model = "roadrunner", weight = 500 },
        { model = "roadrunner2", weight = 500 },
        { model = "roadrunner3", weight = 500 },
        { model = "usssminigun", weight = 500 },
        { model = "usssminigun2", weight = 500 },
        { model = "ussssuv", weight = 500 },
        { model = "ussssuv2", weight = 500 },
        { model = "watchtower", weight = 500 },
        { model = "watchtower2", weight = 500 },
        { model = "usssvan", weight = 1000 },
        { model = "usssvan2", weight = 1000 },
    },
    CAMION = { 
        { model = "vetir", weight = 500 },
        { model = "tiptruck", weight = 500 },
        { model = "tiptruck2", weight = 500 },
        { model = "rubble", weight = 1000 },
        { model = "mixer", weight = 1000 },
        { model = "mixer2", weight = 500 },
        { model = "guardian", weight = 500 },
        { model = "flatbed", weight = 500 },
        { model = "dump", weight = 500 },
        { model = "bulldozer", weight = 500 },
        { model = "benson", weight = 500 },
        { model = "biff", weight = 500 },
        { model = "hauler", weight = 500 },
        { model = "mule", weight = 500 },
        { model = "mule2", weight = 500 },
        { model = "mule3", weight = 500 },
        { model = "mule4", weight = 500 },
        { model = "packer", weight = 1000 },
        { model = "phantom", weight = 1000 },
        { model = "phantom3", weight = 1000 },
        { model = "pounder", weight = 2000 },
        { model = "pounder2", weight = 2000 },
        { model = "towtruck", weight = 500 },
        { model = "towtruck2", weight = 400 },
        { model = "tractor", weight = 10 },
        { model = "tractor2", weight = 1000 },
        { model = "utillitruck", weight = 1000 },
        { model = "utillitruck2", weight = 1000 },
        { model = "utillitruck3", weight = 450 },
        { model = "docktug", weight = 50 },
    },
}

Config.VehiclePlate = {
    taxi = "TAXI",
    cop = "LSPD",
    ambulance = "EMS0",
    mecano = "MECA"
}