fx_version 'adamant'
game 'gta5'

files {
    'RMenu.lua',
    'menu/RageUI.lua',
    'menu/Menu.lua',
    'menu/MenuController.lua',
    'components/Audio.lua',
    'components/Enum.lua',
    'components/Keys.lua',
    'components/Rectangle.lua',
    'components/Sprite.lua',
    'components/Text.lua',
    'components/Visual.lua',
    'menu/elements/ItemsBadge.lua',
    'menu/elements/ItemsColour.lua',
    'menu/elements/PanelColour.lua',
    'menu/items/UIButton.lua',
    'menu/items/UICheckBox.lua',
    'menu/items/UIInfo.lua',
    'menu/items/UIInput.lua',
    'menu/items/UILine.lua',
    'menu/items/UIList.lua',
    'menu/items/UISeparator.lua',
    'menu/items/UISlider.lua',
    'menu/items/UISliderHeritage.lua',
    'menu/items/UISliderProgress.lua',
    'menu/panels/UIColourPanel.lua',
    'menu/panels/UIGridPanel.lua',
    'menu/panels/UIPercentagePanel.lua',
    'menu/panels/UISliderPanel.lua',
    'menu/panels/UISpritPanel.lua',
    'menu/panels/UIStatisticsPanel.lua',
    'menu/windows/UIHeritage.lua',
}